EmptyResponseException: Inherit EndpointException
- Inheritance has been moved from RequestException to EndpointException
  instead, which it probably should have been originally. Especially now
  when we've added more HTTP status exceptions based on EndpointException.

- Documented the exception to explain when it's used.